apikey: ZXZqQmxNRFFzaFVROjM3RHlTTlI2SmdJRw==
apiurl: https://sandbox.e-signlive.com/api
edmsURL: https://edms.acuitys.com/alfresco/api/-default-/public/cmis/versions/1.1/atom
edmsuser: dssserviceaccnt
edmspwd: ACPedms!23
edmspath: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathRETA: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathAAAP: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathGSA: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathIACP: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathSORN: /Sites/agency-concurrence-process/documentLibrary/Signed/
edmspathSalesforce: /Sites/agency-concurrence-process/documentLibrary/Signed/
smtp: smtp.gsa.gov
# Connection parameters
orgNames:
  - AAAP
  - IACP
  - RETA
  - Salesforce
  - GSA
connection:
    apiaaakey: ZXZqQmxNRFFzaFVROjM3RHlTTlI2SmdJRw==
    apiaaaurl: https://sandbox.e-signlive.com/api

# Protocols
protocols:
   - http
   - https

# Users
users:
    tom: passwd
    bob: passwd

#JMS Active MQ Queue
jmsBrokerUrl: tcp://52.205.146.11:61616

#DSS Support email
dssSupportEmail: dsstest@gsa.gov